server {
    listen 8080;

    root /var/www/html;
    index index.html;

    location /healthz {
        access_log off;

        return 200;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
