server {
    listen 8090;

    root /var/www/html;
    access_log off;

    location /metrics {
        add_header Content-Type text/plain;
        add_header Content-Type "text/plain; version=0.0.4; charset=utf-8";
        try_files /metrics.txt =404;
    }
}
