name: Build, Sign and Push to Harbor

on:
  workflow_dispatch:

jobs:
  publish-image:
    uses: myTestOrg0/cosign_workflow/.github/workflows/upload.yaml@main
    with:
      image_name: k8s-hello-secops-test
      harbor_registry: harbor.dev.k8s-dev.org
      team: team-secops
      environment_name: production
      tag: 1.0.4
      harbor_username: robot$team-secops+test
    secrets:
      HARBOR_KEY: ${{ secrets.MY_HARBOR_TOKEN }}
