name: Release image

on:
  workflow_dispatch:

jobs:
  sign-and-release:
    uses: myTestOrg0/cosign_workflow/.github/workflows/upload.yaml@main
    with:
      image_name: harbor.example.com/project/repo1
      image_tag: 1.0.5
      dockerfile: Dockerfile
    secrets:
      harbor_username: "robot$team-secops+test"
      harbor_token: ${{ secrets.MY_HARBOR_TOKEN }}
