name: Build and push K8S-hello to production

run-name: Build and push <your application name>:${{ github.event.release.tag_name }} to production

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build-and-push:
    uses: lidofinance/actions/.github/workflows/k8s-build-push-harbor.yml@<full-commit-sha>
    with:
      tag: ${{ github.event.release.tag_name }}
      branch: main
      registry: registry.prod.k8s-prod.org
      registry_username: ${{ vars.REGISTRY_PROD_USERNAME }}
      image: <harbor-project>/<application-name>
      environment: <github-environment-name>
    secrets:
      registry_token: ${{ secrets.HARBOR_TOKEN }}
