name: Build and push K8S-hello to production

run-name: Build and push K8S-hello:${{ github.event.release.tag_name }} to production

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build-and-push:
    uses: lidofinance/actions/.github/workflows/k8s-build-push-harbor.yml@272d89dcdd920ca26fe4561e0bbda7298f18102e
    with:
      tag: ${{ github.event.release.tag_name }}
      branch: main
      registry: registry.staging.k8s-staging.org
      registry_username: robot$team-secops
      image: team-secops/k8s-hello-secops-test
      environment: harbor_stage_release
    secrets:
      registry_token: ${{ secrets.HARBOR_STAGE_TOKEN }}
